tap "crunchydata/brew"
tap "dbt-labs/dbt"
tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "jakehilborn/jakehilborn"
tap "rainforestapp/public"
brew "age"
brew "autoconf"
brew "automake"
brew "coreutils"
brew "asdf"
brew "awscli"
brew "bash"
brew "berkeley-db", link: true
brew "lz4"
brew "glib"
brew "python@3.9"
brew "openldap"
brew "curl"
brew "deno"
brew "docker", link: false
brew "folly"
brew "fizz"
brew "wangle"
brew "guile"
brew "p11-kit"
brew "unbound"
brew "gnutls"
brew "harfbuzz"
brew "libarchive"
brew "libass"
brew "tesseract"
brew "ffmpeg"
brew "gcc"
brew "gh"
brew "git"
brew "libksba"
brew "gnupg"
brew "python@3.10"
brew "gobject-introspection"
brew "grep"
brew "htop"
brew "jq"
brew "krb5"
brew "libp11"
brew "libpq"
brew "mas"
brew "mitmproxy"
brew "node"
brew "ossp-uuid"
brew "pandoc"
brew "perl"
brew "pipenv"
brew "postgresql@14"
brew "pure"
brew "ruby"
brew "rust"
brew "switchaudio-osx"
brew "telnet"
brew "vim"
brew "watchman"
brew "wget"
brew "yarn"
brew "zlib"
brew "zsh"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"
brew "crunchydata/brew/cb"
brew "heroku/brew/heroku"
brew "jakehilborn/jakehilborn/displayplacer"
brew "rainforestapp/public/rainforest-cli"
cask "1password"
cask "1password-cli"
cask "beyond-compare"
cask "cleanshot"
cask "db-browser-for-sqlite"
cask "docker"
cask "font-meslo-lg"
cask "github"
cask "google-chrome"
cask "iterm2"
cask "keycastr"
cask "mks"
cask "monodraw"
cask "ngrok"
cask "rectangle"
cask "rocket"
cask "slack"
cask "tableplus"
cask "visual-studio-code"
cask "wkhtmltopdf"
cask "xcodes"
mas "1Password for Safari", id: 1569813296
mas "Dato", id: 1470584107
mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "Pixelmator Pro", id: 1289583905
mas "Tag Editor Free", id: 984278082
mas "WhatsApp", id: 1147396723
mas "Xcode", id: 497799835
